import Head from 'next/head'
import Header from '../components/Header'
import styles from '../styles/Home.module.css'
import Image from 'next/image';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Google v-1</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* Header */}
      <Header></Header>
    
      {/* Body */}
      <form>
        <Image src="https://1000marcas.net/wp-content/uploads/2020/02/logo-Google.png" width="300" height="100" />
      </form>

      {/* Footer */}

    </div>
  )
}
